/*
 * This source file was generated by the Gradle 'init' task
 */
package coding.space;

import java.util.UUID;

import com.fasterxml.uuid.Generators;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        UUID uuid = Generators.timeBasedGenerator().generate();
        System.out.println(uuid);
    }
}
